spring:
    application:
        name: gateway
    config:
        import: optional:configserver:http://configserver:8888

management:
    endpoints:
        web:
            exposure:
                include: gateway,metrics,health,logfile
    endpoint:
        gateway:
            enabled: true
    metrics:
        enabled: true
    tracing:
        enabled: true