spring:
  application:
    name: reservation_app

user:
    api:
        host: user
        port: 8090
        url: http://${user.api.host}:${user.api.port}/api/user/  
flight:
    api:
        host: flight
        port: 8091
        url: http://${flight.api.host}:${flight.api.port}/api/flights/  