spring:
    application:
        name: reservation_app
    config:
        import: optional:configserver:http://localhost:8888


user:
    api:
        host: localhost
        port: 8090
        url: http://${user.api.host}:${user.api.port}/api/user/  
flight:
    api:
        host: localhost
        port: 8091
        url: http://${flight.api.host}:${flight.api.port}/api/flights/  