spring:
    cloud:
        gateway:
            routes:
                - id: user_app
                  uri: http://user:8090
                  predicates:
                    - Path=/api/user/** 
                - id: flight_app
                  uri: http://flight:8091
                  predicates:
                    - Path=/api/flights/**
                    - Path=/api/ports/**
                    - Path=/api/flightDetails/**
                - id: reservation_app
                  uri: http://reservation:8092
                  predicates:
                    - Path=/api/reservation/**
                    - Path=/api/passenger/**
                    - Path=/api/reservedFlight/**
            discovery:
                locator:
                    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true


server:
    port: 8222