server:
  port: 8092



spring:
  datasource:
    url:  jdbc:mysql://db:3306/reservation_app
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true


user:
    api:
        host: user
        port: 8090
        url: http://user:8090/api/user/
flight:
    api:
        host: flight
        port: 8091
        url: http://flight:8091/api/flights/  