server:
  port: 8090



spring.:
  datasource:
    url:  jdbc:mysql://db:3306/user_app
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true